Update build-pr-check.yaml

diff --git a/.github/workflows/build-pr-check.yaml b/.github/workflows/build-pr-check.yaml
--- a/.github/workflows/build-pr-check.yaml
+++ b/.github/workflows/build-pr-check.yaml
@@ -95,33 +95,49 @@ jobs:
               #./gradlew core:test --tests 'org.parallel.big.BigExecution6Test' --tests 'org.parallel.huge.HugeExecution3Test' --warning-mode all
               ./gradlew core:test ${{env.image}} --warning-mode all 
 
+      - name: Upload Test Results
+        if: success() || failure() # always run even if the previous step fails
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-results-${{ matrix.runner-index }}
+          path: parallel-backend-tests/build/test-results/test
+
   aggregate-results:
     runs-on: ubuntu-latest
     name: Aggregate test results and cache unified report
     needs: run-parallel-tests
     steps:
-      - name: Install Rejunify
+      - name: Install Node.js and xunit-viewer
         if: success() || failure() # always run even if the previous step fails
         run: |
-          wget https://github.com/sebrock/rejunify/releases/download/v0.2.0/rejunify-x86_64-unknown-linux-musl.tar.gz
-          tar -xzf rejunify-x86_64-unknown-linux-musl.tar.gz
-          sudo mv rejunify /usr/local/bin/
+          npm install -g xunit-viewer
+
       - name: Download Test Results
         if: success() || failure() # always run even if the previous step fails
-        uses: actions/download-artifact@v3
-        with:
-          name: test-results-${{ matrix.runner-index }}
-          path: test-results/
+        run: |
+          for i in $(seq 0 $(( ${{ env.total-runners }} - 1 ))); do
+            echo "Downloading test-results-${i}"
+            gh action download-artifact --name test-results-${i} --path test-results/
+          done
 
-      - name: Merge JUnit Test Reports
+      - name: Merge JUnit Test Reports using xunit-viewer
         if: success() || failure() # always run even if the previous step fails
         run: |
           mkdir -p unified-test-results
-          rejunify -i test-results/ -o unified-test-results/unified-report.xml
+          xunit-viewer -r test-results/ -o unified-test-results/unified-report.xml
+          
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/unified-test-results/test/TEST-*.xml'
+          
+      - name: Cache Unified JUnit Test Reports
+        uses: actions/cache@v3
+        with:
+          path: unified-test-results/
+          key: unified-junit-test-results-${{ github.sha }}
+          restore-keys: |
+            unified-junit-test-results-     
         
               
