Try to configure JUnit to produce more detailed output. (23)

diff --git a/.github/workflows/build-pr-check.yaml b/.github/workflows/build-pr-check.yaml
--- a/.github/workflows/build-pr-check.yaml
+++ b/.github/workflows/build-pr-check.yaml
@@ -93,7 +93,7 @@ jobs:
           glob: parallel-backend-tests/core/**/*Test.java
           split-total: ${{ env.total-runners }}
           split-index: ${{ matrix.runner-index }}
-          junit-path: ${{ env.use_junit_results == 'true' && './unified-test-results/unified-report.xml' || '' }}
+#          junit-path: ${{ env.use_junit_results == 'true' && './downloaded-test-results/**/*.xml' || '' }}
 
       - name: Set image variable for tests
         run: |
@@ -176,17 +176,17 @@ jobs:
           echo "CACHE_UPDATE=false" >> $GITHUB_ENV
         fi    
 
-    - name: Install Python dependencies
-      run: |
-        python -m venv venv
-        source venv/bin/activate
-        pip install junitparser
-
-    - name: Merge JUnit Test Reports
-      run: |
-        python -m venv venv
-        source venv/bin/activate
-        python scripts/merge_junit_reports.py      
+#    - name: Install Python dependencies
+#      run: |
+#        python -m venv venv
+#        source venv/bin/activate
+#        pip install junitparser
+#
+#    - name: Merge JUnit Test Reports
+#      run: |
+#        python -m venv venv
+#        source venv/bin/activate
+#        python scripts/merge_junit_reports.py
 
     - name: Update cache with latest test results (if merging minor to major)
       if: env.CACHE_UPDATE == 'true' && (success() || failure())
@@ -195,14 +195,14 @@ jobs:
         key: junit-${{github.base_ref}}-v1
         save-always: true
         path: |
-          unified-test-results
+          ./downloaded-test-results
 
-    - name: Upload Test Results
-      if: success() || failure() # always run even if the previous step fails
-      uses: actions/upload-artifact@v4
-      with:
-        name: unified-test-results
-        path: unified-test-results
+#    - name: Upload Test Results
+#      if: success() || failure() # always run even if the previous step fails
+#      uses: actions/upload-artifact@v4
+#      with:
+#        name: unified-test-results
+#        path: unified-test-results
 
     - name: Display Test Results in UI
       uses: mikepenz/action-junit-report@v4.3.1
