Try to configure JUnit to produce more detailed output. (25)

diff --git a/.github/workflows/build-pr-check.yaml b/.github/workflows/build-pr-check.yaml
--- a/.github/workflows/build-pr-check.yaml
+++ b/.github/workflows/build-pr-check.yaml
@@ -83,8 +83,8 @@ jobs:
           echo "Cached files:"
           ls -la ./unified-test-results
 #
-#      - name: List JUnit Results Directory
-#        run: ls -R ./unified-test-results
+      - name: List JUnit Results Directory
+        run: ls -R ./unified-test-results
 
       - uses: scruplelesswizard/split-tests@v1-alpha.1
         id: split-tests
@@ -197,12 +197,12 @@ jobs:
         path: |
           ./downloaded-test-results
 
-#    - name: Upload Test Results
-#      if: success() || failure() # always run even if the previous step fails
-#      uses: actions/upload-artifact@v4
-#      with:
-#        name: unified-test-results
-#        path: unified-test-results
+    - name: Upload Test Results
+      if: success() || failure() # always run even if the previous step fails
+      uses: actions/upload-artifact@v4
+      with:
+        name: downloaded-test-results
+        path: downloaded-test-results
 
     - name: Display Test Results in UI
       uses: mikepenz/action-junit-report@v4.3.1
