Update build-pr-check.yaml

diff --git a/.github/workflows/build-pr-check.yaml b/.github/workflows/build-pr-check.yaml
--- a/.github/workflows/build-pr-check.yaml
+++ b/.github/workflows/build-pr-check.yaml
@@ -95,4 +95,33 @@ jobs:
               #./gradlew core:test --tests 'org.parallel.big.BigExecution6Test' --tests 'org.parallel.huge.HugeExecution3Test' --warning-mode all
               ./gradlew core:test ${{env.image}} --warning-mode all 
 
+  aggregate-results:
+    runs-on: ubuntu-latest
+    name: Aggregate test results and cache unified report
+    needs: run-parallel-tests
+    steps:
+      - name: Install Rejunify
+        if: success() || failure() # always run even if the previous step fails
+        run: |
+          wget https://github.com/sebrock/rejunify/releases/download/v0.2.0/rejunify-x86_64-unknown-linux-musl.tar.gz
+          tar -xzf rejunify-x86_64-unknown-linux-musl.tar.gz
+          sudo mv rejunify /usr/local/bin/
+      - name: Download Test Results
+        if: success() || failure() # always run even if the previous step fails
+        uses: actions/download-artifact@v3
+        with:
+          name: test-results-${{ matrix.runner-index }}
+          path: test-results/
+
+      - name: Merge JUnit Test Reports
+        if: success() || failure() # always run even if the previous step fails
+        run: |
+          mkdir -p unified-test-results
+          rejunify -i test-results/ -o unified-test-results/unified-report.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/unified-test-results/test/TEST-*.xml'
+        
               
